extends RefCounted

## The houses, painted by hand, one row of characters per row of graphics tiles.
##
## GENERATED by `tools/house_pins.gd` from a `houses.json` that
## `tools/house_page.py` saved. Do not edit here; paint and regenerate.
##
## A house is the one drawing in Generation II that packs three different
## surfaces into one flat picture: the wall seen face-on, the roof seen from
## above, and on some tilesets the front PITCH of that roof drawn face-on as
## well. Nothing measurable tells them apart, so a person says which is which.
##
## THE ARRANGEMENT IS THE KEY, NEVER A TILE ID. One id is the awning course of
## one house and the eave of another, so a pin cannot reach one drawing without
## reaching the other. A drawing is its whole rectangle of tile ids INCLUDING its
## holes, and two placements of one house carry the same rectangle, so one
## painting serves every placement of it.
##
## THIS IS AN OVERRIDE, exactly as `levels.gd` is an override on the cliff pass.
## Only a drawing a person actually CORRECTED is in here: where the painting
## agreed with what the mod already resolved, nothing is written and the tile
## keeps the answer the passes gave it. 0 drawings corrected, covering 0
## placements; 112 were already right.

## What one painted character means.
const NONE := "."
const WALL := "W"
const PITCH := "P"
const ROOF := "R"
const DOOR := "D"
const FALL_WEST := "<"
const FALL_EAST := ">"
const FALL_NORTH := "^"
const FALL_SOUTH := "v"

## One entry per corrected drawing:
##
##   tileset  the tileset its tile ids belong to
##   tiles    the rectangle of tile ids that identifies it, north row first
##   paint    one string per tile row, a character per tile
##   fall     per tile, how many 8px bands a roof tile stands below the ridge of
##            its own roof. Counted from the painted arrows at generation time,
##            so nobody is ever asked for a number: an arrow and the tiles it
##            covers are the whole of a slope.
const HOUSES: Array = []


## The drawings painted on one tileset. A tile id means nothing without it.
static func of_tileset(number: int) -> Array:
	var out: Array = []
	for house: Dictionary in HOUSES:
		if int(house["tileset"]) == number:
			out.append(house)
	return out
