extends RefCounted

## The houses, painted by hand, one row of characters per row of graphics tiles.
##
## GENERATED by `tools/house_pins.gd` from a `houses.json` that
## `tools/house_page.py` saved. Do not edit here; paint and regenerate.
##
## A house packs different surfaces into one flat picture: the wall, which you
## are looking AT, and the roof, which you are either looking DOWN onto or seeing
## from the FRONT. Nothing measurable tells them apart, so a person says which is
## which.
##
## THE UNIT IS THE PIXEL AND IT HAS TO BE. A hipped roof comes down as a diagonal
## across its tiles, so a tile there is part roof and part wall: read at tile
## resolution, "roof" lifts the top of the wall onto the roof and "wall" cuts the
## corner off the roof. Painted per pixel there is no such choice to get wrong.
##
## THE ARRANGEMENT IS THE KEY, NEVER A TILE ID. One id is the awning course of
## one house and the eave of another, so a pin cannot reach one drawing without
## reaching the other. A drawing is its whole rectangle of tile ids INCLUDING its
## holes, and two placements of one house carry the same rectangle, so one
## painting serves every placement of it.
##
## THIS IS AN OVERRIDE, exactly as `levels.gd` is an override on the cliff pass.
## Only a drawing a person actually CORRECTED is in here: where the painting
## agreed with what the mod already resolved, nothing is written and the tile
## keeps the answer the passes gave it. 0 drawings corrected, covering 0
## placements; 112 were already right.

## What one painted character means. There is no character for a DOOR: a door is
## a wall the player walks through, and walking through is collision, which
## nothing here touches. There is none for a SLOPE either: with wall and roof
## separated per pixel, the top of a column's wall is that column's roof height.
const NONE := "."
const WALL := "W"
const ROOF := "R"
const FRONT := "F"

## One entry per corrected drawing:
##
##   tileset  the tileset its tile ids belong to
##   tiles    the rectangle of tile ids that identifies it, north row first
##   paint    one string per PIXEL row, a character per pixel, so eight rows and
##            eight characters per tile
const HOUSES: Array = []


## The drawings painted on one tileset. A tile id means nothing without it.
static func of_tileset(number: int) -> Array:
	var out: Array = []
	for house: Dictionary in HOUSES:
		if int(house["tileset"]) == number:
			out.append(house)
	return out
