extends RefCounted

## The profile's SECOND table: one pin per tile, from a full pass over every
## tileset in the game.
##
## GENERATED by `tools/pass_pins.py` from the answer files in the survey
## directory, and safe to regenerate. `profile.gd`'s own table is hand-authored
## from the reviewer's measurements and always wins over this one.
##
## Nothing here is extracted from a cartridge. A pin can only ever change how a
## tile LOOKS: collision, warps, triggers and scripts read what they always did.
##
## 70 tiles over 2 tilesets. A tile the pass read as a plain standing
## wall is deliberately absent: the automatic resolution already stands it up,
## and it measures the height off the drawing where a pin would force one.

const TILESETS: Dictionary = {
	5: {
		&"flowers": [42, 43, 84, 85, 94, 95],
		&"ground": [1, 4, 20, 76, 77, 80, 81, 92, 93],
		&"stand": [8, 9, 10, 11, 24, 25, 26, 27],
		&"surface": [2, 3, 5, 18, 19, 21, 38, 39, 41, 47, 50, 51, 54, 57],
		&"tombstone": [40, 55, 56, 63, 78],
		&"void": [16],
	},
	7: {
		&"ground": [1, 17, 66, 67, 68, 69, 80, 81, 82, 83, 84, 85],
		&"roof_edge": [6, 7],
		&"surface": [13, 14, 22, 23, 31, 45, 46, 52, 72, 73, 88, 89],
		&"void": [61],
	},
}


static func pinned_class(tileset_number: int, tile: int) -> StringName:
	var groups: Variant = TILESETS.get(tileset_number, null)
	if not groups is Dictionary:
		return &""
	for shape_class: StringName in (groups as Dictionary):
		var tiles: Variant = (groups as Dictionary)[shape_class]
		if tiles is Array and (tiles as Array).has(tile):
			return shape_class
	return &""
