extends RefCounted

## Drawn stems, one row of characters per row of world pixels.
## GENERATED by `tools/stem_pins.py`. Draw and regenerate; do not edit here.
##
## The row count is how far the bloom above is lifted, so the top row meets the
## bloom and the bottom row meets the ground. `mesher.gd` centres it under the
## bloom, so where the shape sits across its own page does not matter.

const MARK := "#"

const SHAPES: Dictionary = {
	&"flower": [
		"...#....",
		"...#....",
		"..#.....",
	],
}


static func of_class(shape_class: StringName) -> Array:
	return SHAPES.get(shape_class, []) as Array
