extends RefCounted

## The stems, drawn by hand on `tools/stem_page.py`, one row of characters per
## row of world pixels.
##
## GENERATED by `tools/stem_pins.py`. Do not edit here; draw and regenerate.
##
## A flower is drawn LOOKED DOWN ON, so the cartridge draws the bloom and no
## stem: from directly above there is none to see. Carved where it is drawn the
## bloom therefore hangs in the air, and stood on the floor it sits in the grass.
## This is the one shape in the mod put into the world that the cartridge does
## not draw, which is why it is drawn by a person rather than guessed at.
##
## The row count is how far the drawing above it is LIFTED, so the top row meets
## the bloom and the bottom row meets the ground and there is no float either
## end. Where the shape sits across its own page does not matter: `mesher.gd`
## centres it under the middle of the bloom it holds up.

const MARK := "#"

const SHAPES: Dictionary = {
	&"flower": [
		"...#....",
		"...#....",
		"...#....",
		"...#....",
		"...#....",
		"...#....",
		"...#....",
		"..#.....",
		"..#.....",
		"..#.....",
	],
}


## The rows a class's stem is drawn on, top first, or an empty array
## where it has none.
static func of_class(shape_class: StringName) -> Array:
	return SHAPES.get(shape_class, []) as Array
