extends RefCounted

## The stems, drawn by hand on `tools/stem_page.py`, one row of characters per
## row of world pixels.
##
## GENERATED by `tools/stem_pins.py`. Do not edit here; draw and regenerate.
##
## A flower is drawn looked down on, so the cartridge draws the bloom and no
## stem. Carved where it is drawn the bloom hangs in the air; stood on the floor
## it sits in the grass. It is drawn by a person because a stem is thin and it
## bends and no number says either.
##
## The row count is how far the bloom above it is lifted, so the top row meets the
## bloom and the bottom row meets the ground. Where the shape sits across its own
## page does not matter: `mesher.gd` centres it under the bloom.

const MARK := "#"

const SHAPES: Dictionary = {
	&"flower": [
		"...#....",
		"...#....",
		"..#.....",
	],
}


## The rows a class's stem is drawn on, top first, or an empty array
## where it has none.
static func of_class(shape_class: StringName) -> Array:
	return SHAPES.get(shape_class, []) as Array
