extends RefCounted

## Painted houses, one row of characters per row of graphics tiles.
## GENERATED by `tools/house_pins.gd`. Paint and regenerate; do not edit here.
## The alphabet is `classes.gd`'s HOUSE_ marks.

## Per drawing: `id`, `tileset`, the `tiles` rectangle that identifies it north
## row first, and `paint`, one string per pixel row.
const HOUSES: Array = []


static func of_tileset(number: int) -> Array:
	var out: Array = []
	for house: Dictionary in HOUSES:
		if int(house["tileset"]) == number:
			out.append(house)
	return out
