extends RefCounted

## One shape pin per tile, over every tileset. `profile.gd` overrides this.
## GENERATED by `tools/pass_pins.py`. Survey and regenerate; do not edit here.
##
## A pin only changes how a tile LOOKS. A tile the pass read as a plain standing
## wall is absent: the automatic resolution stands it up and measures its height.

const TILESETS: Dictionary = {}


static func pinned_class(tileset_number: int, tile: int) -> StringName:
	var groups: Variant = TILESETS.get(tileset_number, null)
	if not groups is Dictionary:
		return &""
	for shape_class: StringName in (groups as Dictionary):
		var tiles: Variant = (groups as Dictionary)[shape_class]
		if tiles is Array and (tiles as Array).has(tile):
			return shape_class
	return &""
