#!/usr/bin/env python3
"""Turns a full pass over the tilesets into the profile's second table.

`survey_pass.py` writes the brief, an agent reads every tile's picture and
answers `ts<n> <tile> <word> <confidence> <words>`, and this turns those lines
into pins. It writes `shape/profile_pass.gd`, which the profile falls back to:
the hand table always wins, because it was authored from the reviewer's own
measurements, and this one is replaceable by re-running the pass.

    tools/pass_pins.py <pass dir> [--write]

Without `--write` it only reports what it would do. What it deliberately does
NOT pin:

  wall                 the automatic resolution already stands a blocked tile
                       up, and it MEASURES the height off the drawing where a
                       pin would force one. A pin that agrees with the default
                       is worse than no pin.
  unsure               goes in front of the human instead.
"""

import collections
import pathlib
import re
import sys

# What each word of the vocabulary becomes. A few become one of several classes
# depending on what the words say the thing IS, because a bollard and a bush are
# both `stand` and are not the same shape.
DIRECT = {
    "floor": "ground",
    "water": "water",
    "void": "void",
    "ledge": "ledge",
    "facade": "facade",
    "roof_flat": "roof",
    "roof_edge": "roof_edge",
    "roof_corner": "roof_corner",
    "top": "surface",
    "on_top_of_furniture": "on_furniture",
    "stairs": "stairs",
}
STANDING = [
    (("bollard", "pole", "post"), "post"),
    (("signpost", "sign"), "sign_post"),
    (("hedge", "bush", "shrub"), "bush"),
    (("sapling", "tree"), "sapling"),
    (("tombstone", "gravestone", "grave"), "tombstone"),
    (("statue", "sculpture"), "statue"),
]
LYING = [
    (("plant pot", "potted", "planter"), "planter"),
    (("flower", "basket", "bed"), "flowers"),
]
SKIP = {"wall", "unsure"}

HEADER = '''extends RefCounted

## The profile's SECOND table: one pin per tile, from a full pass over every
## tileset in the game.
##
## GENERATED by `tools/pass_pins.py` from the answer files in the survey
## directory, and safe to regenerate. `profile.gd`'s own table is hand-authored
## from the reviewer's measurements and always wins over this one.
##
## Nothing here is extracted from a cartridge. A pin can only ever change how a
## tile LOOKS: collision, warps, triggers and scripts read what they always did.
##
## {tiles} tiles over {sets} tilesets. A tile the pass read as a plain standing
## wall is deliberately absent: the automatic resolution already stands it up,
## and it measures the height off the drawing where a pin would force one.

const TILESETS: Dictionary = {{
{body}}}


static func pinned_class(tileset_number: int, tile: int) -> StringName:
\tvar groups: Variant = TILESETS.get(tileset_number, null)
\tif not groups is Dictionary:
\t\treturn &""
\tfor shape_class: StringName in (groups as Dictionary):
\t\tvar tiles: Variant = (groups as Dictionary)[shape_class]
\t\tif tiles is Array and (tiles as Array).has(tile):
\t\t\treturn shape_class
\treturn &""
'''


def classify(word, words):
    if word in SKIP:
        return None
    if word in DIRECT:
        return DIRECT[word]
    table = STANDING if word == "stand" else (LYING if word == "lie" else [])
    for keys, shape_class in table:
        if any(key in words for key in keys):
            return shape_class
    if word == "stand":
        return "stand"
    if word == "lie":
        return "lie"
    return None


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 1
    directory = pathlib.Path(sys.argv[1])
    pins = {}
    counts = collections.Counter()
    furniture = []
    doubts = 0
    for path in sorted(p for p in directory.glob("pass_ts*.txt")
                       if p.stem[7:].isdigit()):
        for line in path.read_text().splitlines():
            fields = line.split(None, 4)
            if len(fields) < 4 or not fields[0].startswith("ts"):
                continue
            number, tile = int(fields[0][2:]), int(fields[1])
            word, confidence = fields[2], fields[3]
            words = (fields[4] if len(fields) > 4 else "").lower()
            counts[word] += 1
            if confidence == "unsure" or word == "unsure":
                doubts += 1
                continue
            if word == "on_top_of_furniture":
                furniture.append((number, tile, words))
            shape_class = classify(word, words)
            if shape_class is None:
                continue
            pins.setdefault(number, {}).setdefault(shape_class, []).append(tile)

    body = []
    total = 0
    for number in sorted(pins):
        body.append("\t%d: {" % number)
        for shape_class in sorted(pins[number]):
            tiles = sorted(set(pins[number][shape_class]))
            total += len(tiles)
            listed = ", ".join(str(t) for t in tiles)
            line = '\t\t&"%s": [%s],' % (shape_class, listed)
            if len(line) <= 88:
                body.append(line)
                continue
            body.append('\t\t&"%s": [' % shape_class)
            row = "\t\t\t"
            for tile in tiles:
                if len(row) + len(str(tile)) + 2 > 88:
                    body.append(row.rstrip())
                    row = "\t\t\t"
                row += "%d, " % tile
            body.append(row.rstrip())
            body.append("\t\t],")
        body.append("\t},")

    print("%d pins over %d tilesets" % (total, len(pins)))
    print("words:", dict(counts))
    print("left to the human (unsure): %d" % doubts)
    print("standing on furniture: %d" % len(furniture))
    if "--write" not in sys.argv:
        print("\n(dry run; pass --write to write profile_pass.gd)")
        return 0

    out = pathlib.Path(__file__).resolve().parent.parent \
        / "mods/voxel3d/shape/profile_pass.gd"
    out.write_text(HEADER.format(
        tiles=total, sets=len(pins), body="\n".join(body) + "\n"
    ))
    print(out)
    listing = directory / "furniture.txt"
    listing.write_text("".join(
        "ts%d %d %s\n" % row for row in sorted(furniture)
    ))
    print(listing)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
