#!/usr/bin/env python3
"""Turns a stem drawn on `tools/stem_page.py` into `shape/stems.gd`.

  stem_pins.py <stem.txt> <class> [<mod root>]

The text is what the page saved: one line a row, `#` for a pixel of stem and `.`
for nothing, top row first. Blank rows are trimmed off the top and the bottom,
so the shape a person drew is the shape that is built however much of the page
they used, and the row count IS how far the drawing above it is lifted.
"""

import os
import sys

HEADER = '''extends RefCounted

## Drawn stems, one row of characters per row of world pixels.
## GENERATED by `tools/stem_pins.py`. Draw and regenerate; do not edit here.
##
## The row count is how far the bloom above is lifted, so the top row meets the
## bloom and the bottom row meets the ground. `mesher.gd` centres it under the
## bloom, so where the shape sits across its own page does not matter.

const MARK := "#"

'''


def load(path):
    rows = [line.rstrip("\n") for line in open(path)]
    while rows and "#" not in rows[0]:
        rows.pop(0)
    while rows and "#" not in rows[-1]:
        rows.pop()
    return rows


def main(argv):
    if len(argv) < 3:
        print(__doc__)
        return 1
    rows = load(argv[1])
    if not rows:
        print("nothing drawn in", argv[1])
        return 1
    name = argv[2]
    root = argv[3] if len(argv) > 3 else os.path.join("mods", "voxel3d")
    wide = max(len(row) for row in rows)
    rows = [row.ljust(wide, ".") for row in rows]
    body = HEADER + "const SHAPES: Dictionary = {\n\t&\"%s\": [\n" % name
    for row in rows:
        body += '\t\t"%s",\n' % row
    body += "\t],\n}\n\n\n"
    body += (
        "## The rows a class's stem is drawn on, top first, or an empty array\n"
        "## where it has none.\n"
        "static func of_class(shape_class: StringName) -> Array:\n"
        "\treturn SHAPES.get(shape_class, []) as Array\n"
    )
    out = os.path.join(root, "shape", "stems.gd")
    open(out, "w").write(body)
    print(out, "%s: %d x %d, %d pixels"
          % (name, wide, len(rows), sum(row.count("#") for row in rows)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
